# Generated by Django 3.0.6 on 2020-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lang', models.CharField(max_length=5)),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
            ],
        ),
    ]
