# Generated by Django 3.0.6 on 2020-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tts',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
